-- ########## EXTENSIONS ##########
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ########## TABLES ##########
CREATE TABLE IF NOT EXISTS "TRANSACTIONS" (
    "ID" UUID NOT NULL,
    "ACCOUNT_ID" UUID NOT NULL,
    "AMOUNT" NUMERIC(10,2) NOT NULL,
    "CURRENCY" VARCHAR(3) NOT NULL,
    "DATE" timestamp NOT NULL,
    PRIMARY KEY ("ID")
);